name: Publish build artifacts

# Run this workflow every time a tag is created/pushed
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    # Name the Job
    name: Build tagged commit and upload the artifacts
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # bring in all history because the gradle versions plugin needs to "walk back" to the closest ancestor tag
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Build and publish
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
        run: |
          ./gradlew publish --no-daemon
